# -----------------------------------------------------------------------------
# Site settings
# -----------------------------------------------------------------------------

title: blank # 网站标题保持空白,将使用全名
first_name: Benyun
middle_name: 
last_name: Zhao
email: benyun.zhao@link.cuhk.edu.hk  # 使用学校邮箱
description: > # 个人简介
  PhD Candidate at CUHK, focusing on computer vision and robotics applications.
footer_text: >
  Powered by <a href="https://jekyllrb.com/" target="_blank">Jekyll</a> with <a href="https://github.com/alshedivat/al-folio">al-folio</a> theme.
keywords: computer vision, robotics, unmanned systems, 3D reconstruction # 关键词
lang: en # 语言设置

url: https://ZhaoBenyun.github.io # GitHub Pages URL
baseurl: /main-site # 子路径

# -----------------------------------------------------------------------------
# Social integration
# -----------------------------------------------------------------------------

github_username: ZhaoBenyun # GitHub用户名
scholar_userid: qc6CJjYAAAAJ # Google Scholar ID

# -----------------------------------------------------------------------------
# Blog
# -----------------------------------------------------------------------------

blog_name: Benyun's Blog # 博客名称
blog_description: Research notes and technical posts about computer vision and robotics

# -----------------------------------------------------------------------------
# Collections
# -----------------------------------------------------------------------------

collections:
  news:
    defaults:
      layout: post
    output: true
    permalink: /:collection/:title/
  projects:
    output: true
    permalink: /:collection/:title/

# -----------------------------------------------------------------------------
# Optional Features
# -----------------------------------------------------------------------------

enable_math: true # 启用数学公式
enable_darkmode: true # 启用暗色模式
enable_navbar_social: true # 在导航栏显示社交链接
enable_project_categories: true # 启用项目分类
enable_medium_zoom: true # 启用图片缩放

# -----------------------------------------------------------------------------
# Jekyll Scholar
# -----------------------------------------------------------------------------

scholar:
  last_name: [Zhao]
  first_name: [Benyun, B.]

  style: apa
  locale: en

  source: /_bibliography/
  bibliography: papers.bib
  bibliography_template: bib

  replace_strings: true
  join_strings: true

  details_dir: bibliography
  details_layout: bibtex.html
  details_link: Details

  query: "@*"
  group_by: year
  group_order: descending
