# -----------------------------------------------------------------------------
# Site settings
# -----------------------------------------------------------------------------

title: blank # 网站标题保持空白,将使用全名
first_name: Benyun
middle_name: 
last_name: ZHAO
email: byzhao@mae.cuhk.edu.hk
description: > # 个人简介
  Ph.D. Candidate at CUHK USR Group, focusing on unmanned systems applications, 
  image processing, and 3D scene understanding. Member of Hong Kong Centre for 
  Logistics Robotics (HKCLR), supervised by Prof. Ben M. Chen.
footer_text: >
  Powered by <a href="https://jekyllrb.com/" target="_blank">Jekyll</a> with <a href="https://github.com/alshedivat/al-folio">al-folio</a> theme.
keywords: unmanned systems, computer vision, robotics, 3D scene understanding, image processing
lang: en

url: https://ZhaoBenyun.github.io
baseurl: /main-site

# -----------------------------------------------------------------------------
# Social integration
# -----------------------------------------------------------------------------

github_username: ZhaoBenyun
scholar_userid: # Google Scholar ID if available
wechat_qr: Claude_ZBY

contact_note: >
  Contact via email or WeChat (微信): Claude_ZBY
  Phone: (852) 67535779

# -----------------------------------------------------------------------------
# Blog
# -----------------------------------------------------------------------------

blog_name: Benyun's Blog
blog_description: Research notes and technical posts about unmanned systems and computer vision

# -----------------------------------------------------------------------------
# Collections
# -----------------------------------------------------------------------------

collections:
  news:
    defaults:
      layout: post
    output: true
    permalink: /:collection/:title/
  projects:
    output: true
    permalink: /:collection/:title/

# -----------------------------------------------------------------------------
# Optional Features
# -----------------------------------------------------------------------------

enable_math: true
enable_darkmode: true
enable_navbar_social: true
enable_project_categories: true
enable_medium_zoom: true

# -----------------------------------------------------------------------------
# Jekyll Scholar
# -----------------------------------------------------------------------------

scholar:
  last_name: [ZHAO]
  first_name: [Benyun, B.]

  style: apa
  locale: en

  source: /_bibliography/
  bibliography: papers.bib
  bibliography_template: bib

  replace_strings: true
  join_strings: true

  details_dir: bibliography
  details_layout: bibtex.html
  details_link: Details

  query: "@*"
  group_by: year
  group_order: descending
